export { traverseIterative } from './traverse-iterative.js'
export type { TraverseBudget, IterativeVisit } from './traverse-iterative.js'
export { buildPrepareIndex } from './prepare-index.js'
export { classifyRegion, applyRegionClassification, groupMaximalRegions } from './prepare-node.js'
export { prepareView, getPreparedSources, bindPreparedSources, listPreparedNodes } from './prepare-view.js'
export type { PrepareViewOptions } from './prepare-view.js'
export { collectNodeExpressionSources, compileExpressionSources } from './prepare-expression.js'
export { compileNodeActions } from './prepare-action.js'
export { compileLoopPlan } from './prepare-loop.js'
export { compileSlotPlan } from './prepare-slot.js'
export { recompileIncremental, collectAffectedIds, reuseUnaffected } from './incremental/index.js'
export { EVENT_MODIFIERS, assertSupportedModifiers } from './event-modifiers.js'
